plugins {
   id 'java'
   id 'application'
   id 'org.ajoberstar.git-publish' version '4.2.0'
}

repositories {
    mavenCentral()
}


java {
    sourceCompatibility = JavaVersion.toVersion(11)
    targetCompatibility = JavaVersion.toVersion(11)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
    testLogging {
        events "passed", "skipped", "failed"
        }
}

application { //Allows  ./gradlew run --args=path-to-test-data
    mainClass = 'edu.odu.cs.MostCommonWords'
}



tasks.register('reports') {
    dependsOn 'build'
    dependsOn 'javadoc'

    copy {
        from 'src/main/html'
        into 'reports/'
    }

    copy {
        from 'build/docs/'
        into 'reports/'
    }
}

tasks.register('deployReports') {
    dependsOn 'reports'
    dependsOn 'gitPublish'

    gitPublishCopy.dependsOn 'build'
    gitPublish {
        repoUri = 'git@github.com:ODU-CS351-F26/CS351--exercise-documentation--ryanmf2.git'

        branch = 'gh-pages'

        contents {
            from 'build/reports'
        }
    }
}